### ISSUE TITLE
exceptions not showing up in sentry

### ISSUE THREAD

**Issue by cityzen** [getsentry/sentry-laravel#2] opened 2016-04-28 12:31 UTC
I was using the raven package before with the configureMonologUsing method which was working fine. I replaced that with this package and not seeing exceptions in the sentry control panel.

This is on a local dev environment and I'm happy to provide more info or test anything that needs to be tested.

**Comment by dcramer** [comment] 2016-04-28 12:34
Can you confirm the laravel version and where the DSN is configured?






On Thu, Apr 28, 2016 at 5:31 AM -0700, "Mike Hughes" <notifications@github.com> wrote:












I was using the raven package before with the configureMonologUsing method which was working fine. I replaced that with this package and not seeing exceptions in the sentry control panel.



This is on a local dev environment and I'm happy to provide more info or test anything that needs to be tested.

**Comment by cityzen** [comment] 2016-04-28 12:54
Sure, I'm on Laravel version 5.1.22 and in my config i have:
`'dsn' => env('SENTRY_DSN'),`

and in my .env:
`SENTRY_DSN=https://....@app.getsentry.com/....`

**Comment by cityzen** [comment] 2016-04-28 21:08
Should I go ahead and revert back to using monolog's raven handler or is this an issue you're able to replicate?

**Comment by dcramer** [comment] 2016-04-29 08:06
@cityzen looking into this, including improving logging so you can determine if its fully and properly configured

Is it possible that the errors you're seeing aren't actual exceptions and are simply things reported with Log::error ?

**Comment by dcramer** [comment] 2016-04-29 08:14
Current dev-master has a ``Log::info`` call which records the Sentry SDK registration. I added a laravel 5.1 example as well. Unable to reproduce any issues atm.

**Comment by hdra** [comment] 2016-05-09 08:57
I experienced the same issue earlier today. To reproduce it, simply setup sentry with the bare minimum config like the one in the getting started docs (with only the `dsn` var setup). 

The issue is the `Raven_Client` constructor not parsing the DSN because the first param in it is passed as an array (and making variables like `server` being left as null). 

My quick and dirty fix is simply by creating my own service provider to register the sentry service. Basically, replacing `$client = new \Raven_Client($config);` line with `$client = new \Raven_Client($user_config['dsn'], $config);`.

I would've sent a PR for this, but I'm not sure what kind of fix you're looking for. For example, currently the error capture would fail silently if the `Raven_Client::server` is not set (the `send` method would simply return false), which I think shouldn't be the case.

**Comment by dcramer** [comment] 2016-05-09 16:45
@hdra the current sentry-php client allows the first param to be a dsn or an array (with a dsn key), is it possible you were somehow using an older version?

**Comment by hdra** [comment] 2016-05-09 23:44
@dcramer You're right. I'm not on the latest. Thanks.

Has this change been published to Packagist, btw?

**Comment by dcramer** [comment] 2016-05-09 23:45
It definitely should be there, but also I thought we had locked in the version requirement here in sentry-laravel. I will revisit this stuff tomorrow to ensure thats true.

**Comment by paszczus** [comment] 2016-06-10 13:45
We are also having similar problem. We have configured DSN and we are using Laravel 5.2.36 version and Exceptions are not stored in Sentry (7.7.0). In nginx logs on Sentry we are seeing: 

`10.59.146.75 - - [10/Jun/2016:15:39:55 +0200] "POST /api/16/store/ HTTP/1.0" 403 55 "-" "sentry-php/0.21.1" "217.173.x.x"`

But DSN is 100% good (we have tried with new project and existing one). We have also tested dev-master version of this project but still with no luck. What else we can do to get it running?
Thanks!

**Comment by paszczus** [comment] 2016-06-10 14:12
In tcpdump we see:

```
Host: foo.bar.pl
X-Real-IP: 217.173.x.x
X-Forwarded-For: 217.173.x.x
Connection: close
Content-Length: 8332
Accept: */*
User-Agent: sentry-php/0.21.1
X-Sentry-Auth: Sentry sentry_timestamp=1465567735.081852, sentry_client=sentry-php/0.21.1, sentry_version=6, sentry_key=secretkey, sentry_secret=secret
Content-Encoding: gzip
Content-Type: application/octet-stream

eJztPQlz4sbSf0Wh/D3jPMASl423nAQDtvGaY4Ww14QtSkgDyAhJkYSvzf73r3t0gzjseLN5KYg3iDl6enr6mp5DXxNzi5iJk68JRU6cJDpC+vgozbH6/G7SPrq+1s+0GmkXH+xGWtXHipa2iWXPNUU3dJUYaiKVkEVbxOrGxKiUO/jkAEyIMpn+BkUztGyGFhZt21SGcwACBcqmKT4z+ohRiTa2J8xR4tu3b6mESf6YQyMIaUbsiY5oXdQEqD03VXie2LZx0j/sHxqiRtRMuIX+IZSC2ubzwIKGtDEUhxRJ16cKNvk1MRiLCK7MZXKZQrZ0nCvljjNcPn+Uy+WPCiwUHgxeVGlGidG7Hl0/GvbtlV79TAzIa1+2O7VOp16FzJ/dDyR/7vDnaaH1sdaEdPJ8ZchKvVhXrOdml6/1VOO8ofET/l4WO9r46e7zTbubk0rtTt2qa73J8PJGrd/ryo3Q1G5UgyNd9VnKyl3h/spoXfKGmJMK4ucb7mOu+XCTm9wKwvhpOJWvu7cFnVzIdw31qsjnrmZ89ka7YyeGVFVtkYXWZnrupjrRe+ynZ3I+ue2xN2bvlq/0Ls+yrdrTjXxTc3CYcZO7Z8B31rtvVafZxn2t0MjW2bvbRqF3e/fYu58+Nmb1QvNFYntCI9u87c0a9w22ma29NF9qXE/oTZvCp+xdtsE1LxrwfaP27u+4xkv3sSfcKaNPp6dAI1U0xQeiDixiWYquhQmlSY/8rNBtXU4KN+ePD59ur85ITcp1uj2uyzX5tsAq15Wr7N3tE9frIKIGL13Y971LwxAvbLVTvXscZm+aN4KU5XNym8wKH4fTx2z3dpwbdtmcdH/2Mryocz316vMw16z3zq+qzc9N5e7lrPApO5mSKW/falcVcfopf3thnJFq85MsyEAAvjFkm9efulc5FwcbiKK0lPpjo9rNNQT5vnGLcO4KDSBWM9tg74Qy17q4e24KNR
```

and then

```
Server: nginx/1.6.3
Date: Fri, 10 Jun 2016 14:08:55 GMT
Content-Type: text/plain
Connection: close
Expires: Fri, 10 Jun 2016 14:08:55 GMT
Content-Language: en
X-Sentry-Error: Bad data decoding request (IOError, Not a gzipped file)
Vary: Accept-Language, Cookie
Last-Modified: Fri, 10 Jun 2016 14:08:55 GMT
Cache-Control: max-age=0

Bad data decoding request (IOError, Not a gzipped file)
```

**Comment by dcramer** [comment] 2016-06-10 17:35
@paszczus your issue is resolved in sentry-php@0.21.2, sorry about that!

**Comment by paszczus** [comment] 2016-06-10 18:26
@dcramer thank you! It is working fine now! Yeah!

**Comment by dcramer** [comment] 2016-07-26 23:34
Closing this out, lets open with new details if theres anything remaining bits.

**Closed by dcramer** 2016-07-26 23:34 UTC
