### ISSUE TITLE
Metrics are not flushed when used in jobs

### ISSUE THREAD

**Issue by pataar** [getsentry/sentry-laravel#907] opened 2024-06-07 17:58 UTC
### How do you use Sentry?

Self-hosted / on-premises

### SDK version

4.5.1

### Steps to reproduce

1. Use metrics in async jobs
2. See that they're not being pushed to Sentry

### Expected result

I was expecting results when using metrics in an Event listener that's fired in a job. Job is done async using the database driver.

### Actual result

The metric doesn't get posted to Sentry. Might be because of a missing flush. Metrics done using normal requests are handled correctly.

**Comment by stayallive** [comment] 2024-06-08 05:01
Interesting that this is your second queue related bug. Seems like your project might do something non-standard in its queue operations. 

What Laravel version are you using and can you maybe show me a minimal reproducible example so I can try to replicate?

We are flushing metrics after job execution (and I know this to be working in production applications) but we might be missing something or missing something for a specific Laravel version.

**Comment by pataar** [comment] 2024-06-08 06:14
> Interesting that this is your second queue related bug. Seems like your project might do something non-standard in its queue operations.
> 
> What Laravel version are you using and can you maybe show me a minimal reproducible example so I can try to replicate?
> 
> We are flushing metrics after job execution (and I know this to be working in production applications) but we might be missing something or missing something for a specific Laravel version.

Using Laravel version v10.48.12. PHP version 8.3. We're executing jobs using 6 replicated pods in Kubernetes that run the `php /var/www/artisan queue:work database --sleep=3 --tries=3` method.

One thing that might be relevant is that we're executing metrics in EventListeners as follows:

```php
class AppUserPushNotificationSentListener {
	/**
	 * Create the event listener.
	 */
	public function __construct() {}

	/**
	 * Handle the event.
	 */
	public function handle(AppUserPushNotificationSent $event): void {
		$currentInstance = CurrentInstance::get();

		metrics()->increment(
			key: 'push_notification_sent',
			value: $event->nativeDevicesCount,
			tags: [
				'instance_url_prefix' => $currentInstance?->getUrlPrefix(),
				'instance_id' => $currentInstance?->getId(),
				'treatment_id' => $event->notification->treatment_id,
				'is_background' => $event->notification->is_background,
			],
		);
	}
}

```

**Comment by pataar** [comment] 2024-06-08 11:11
@stayallive does the sampling rate affect metrics?

**Comment by pataar** [comment] 2024-06-08 11:55
<img width="1132" alt="Screenshot 2024-06-08 at 13 54 34" src="https://github.com/getsentry/sentry-laravel/assets/3403851/7c40bb03-c68a-47dd-bb13-137d84011d6e">

Think I've found the issue. Tags must use string values.

**Comment by stayallive** [comment] 2024-06-08 19:54
Ah yes, we try to communicate that with a docblock since there is not a perfect way to ensure that is the case in PHP otherwise: https://github.com/getsentry/sentry-php/blob/1ea8e3d8ec549de508b3644cd09dbc251bd53b0f/src/Metrics/Metrics.php#L43

And those warnings seems like a great way to surface those errors without us adding type checks that might crash your application if you send wrong tags.

I'll close this one for now, since I think this is not an issue with the SDK and metrics are flushed as expected in jobs.

**Closed by stayallive** 2024-06-08 19:54 UTC
Labels: Waiting for: Product Owner

**Comment by pataar** [comment] 2024-06-11 08:17
Seems to work now 😁
