### ISSUE TITLE
Real ip address in user data

### ISSUE THREAD

**Issue by OrishS** [getsentry/sentry-laravel#444] opened 2021-01-07 16:52 UTC
Hello,

In \Sentry\Integration\RequestIntegration::processEvent there is REMOTE_ADDR passed as user ip. It causes an issue on servers behind proxy like load balancer, because then value of REMOTE_ADDR is proxy ip. Is there a way to provide any other value there, like value from HTTP_X_FORWARDED_FOR?

**Comment by adam1010** [comment] 2021-01-22 21:41
Yes `before_send` looks like a good patch for users to use until the SDK fixes the issue (I posted example code here: https://github.com/getsentry/sentry-laravel/issues/133#issuecomment-765596374)  Thank you!!!!

Laravel inherits from Symfony's Request class, so the code you linked to for how the Symfony SDK handles this can be easily ported over to the Laravel SDK.

**Comment by stayallive** [comment] 2021-01-23 11:46
I am looking into this again, thanks for the pointers and information but I am closing this issue because it's a duplicate of #133. Will continue the discussion there!

**Closed by stayallive** 2021-01-23 11:46 UTC
