### ISSUE TITLE
Duplicate exceptions

### ISSUE THREAD

**Issue by dcramer** [getsentry/sentry-laravel#87] opened 2017-07-26 13:56 UTC
In some cases we throw duplicate-ish exceptions. For example, if you unset APP_KEY:

```
RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
#15 vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(43): __construct
#14 vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(27): Illuminate\Encryption\{closure}
#13 vendor/laravel/framework/src/Illuminate/Container/Container.php(726): build
#12 vendor/laravel/framework/src/Illuminate/Container/Container.php(608): resolve
#11 vendor/laravel/framework/src/Illuminate/Container/Container.php(575): make
#10 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): make
#9 vendor/laravel/framework/src/Illuminate/Container/Container.php(862): resolveClass
#8 vendor/laravel/framework/src/Illuminate/Container/Container.php(790): resolveDependencies
#7 vendor/laravel/framework/src/Illuminate/Container/Container.php(758): build
#6 vendor/laravel/framework/src/Illuminate/Container/Container.php(608): resolve
#5 vendor/laravel/framework/src/Illuminate/Container/Container.php(575): make
#4 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): make
#3 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(215): terminateMiddleware
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(189): terminate
#1 public/index.php(58): require_once
#0 server.php(21): null
```

and

```
RuntimeException: The only supported ciphers are AES-128-CBC and AES-256-CBC with the correct key lengths.
#36 vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php(43): __construct
#35 vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(27): Illuminate\Encryption\{closure}
#34 vendor/laravel/framework/src/Illuminate/Container/Container.php(726): build
#33 vendor/laravel/framework/src/Illuminate/Container/Container.php(608): resolve
#32 vendor/laravel/framework/src/Illuminate/Container/Container.php(575): make
#31 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): make
#30 vendor/laravel/framework/src/Illuminate/Container/Container.php(862): resolveClass
#29 vendor/laravel/framework/src/Illuminate/Container/Container.php(790): resolveDependencies
#28 vendor/laravel/framework/src/Illuminate/Container/Container.php(758): build
#27 vendor/laravel/framework/src/Illuminate/Container/Container.php(608): resolve
#26 vendor/laravel/framework/src/Illuminate/Container/Container.php(575): make
#25 vendor/laravel/framework/src/Illuminate/Foundation/Application.php(728): make
#24 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(138): Illuminate\Pipeline\{closure}
#23 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#22 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#21 vendor/laravel/framework/src/Illuminate/Routing/Router.php(576): runRouteWithinStack
#20 vendor/laravel/framework/src/Illuminate/Routing/Router.php(535): dispatchToRoute
#19 vendor/laravel/framework/src/Illuminate/Routing/Router.php(513): dispatch
#18 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Foundation\Http\{closure}
#17 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\{closure}
#16 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): handle
#15 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\{closure}
#14 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#13 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): handle
#12 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\{closure}
#11 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#10 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): handle
#9 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\{closure}
#8 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#7 vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): handle
#6 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(148): Illuminate\Pipeline\{closure}
#5 vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Routing\{closure}
#4 vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): then
#3 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): sendRequestThroughRouter
#2 vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): handle
#1 public/index.php(54): require_once
#0 server.php(21): null
Richcurl
```

**Comment by dcramer** [comment] 2017-07-26 13:56
Not sure if we can actually do anything here

**Comment by stayallive** [comment] 2017-09-15 09:13
Related #408, this occurs on PHP 7+ and looks to be avoidable.

**Comment by Jean85** [comment] 2017-10-30 08:50
This seems to happen in the Symfony integration too... https://github.com/getsentry/sentry-symfony/issues/48

**Comment by stayallive** [comment] 2017-10-30 09:03
@Jean85 I think this has something to do with how PHP 7 handles fatal errors (which can be catchable). getsentry/sentry-php#408 <- been trying to find a reproducable case but having a hard time.

**Comment by Jean85** [comment] 2017-10-30 09:04
Maybe it's **not** plan PHP's fault? I was thinking that maybe the issue is related to Symfony's ErrorHandler, that re-throws errors as exceptions for BC. Does Laravel use it too?

**Comment by stayallive** [comment] 2017-10-30 09:06
Yes, that was my thought too (and yes Laravel uses it too sort-of) but the sentry-php issue is for WordPress that's why I am looking also in the plain PHP direction for the root cause.

**Comment by stayallive** [comment] 2017-11-09 18:09
With sentry-php version 1.8.1 just released, this should be fixed (run composer update). If it still persists for anyone, please open an new issue with some info on the error that is duplicated.

**Closed by stayallive** 2017-11-09 18:09 UTC
