### ISSUE TITLE
Sentry-Laravel breaks Artisan

### ISSUE THREAD

**Issue by mitsuhiko** [getsentry/sentry-laravel#20] opened 2016-06-23 14:02 UTC
From a support issue: Using Sentry with Laravel 5.2 on macOS breaks artisan.

The moment I comment out the "Sentry\SentryLaravel\SentryLaravelServiceProvider::class," and "'Sentry' => Sentry\SentryLaravel\SentryFacade::class," from the app.php file, artisan starts working again.

**Comment by darkgoldblade01** [comment] 2016-06-23 16:40
On macOS 10.12 beta 1, and OSX 10.11 (current version available) it breaks.

I can provide the `composer.json` for your internal tracking, but we were really excited to get this up and running. It works on our server, running Ubuntu 14.04.4 x64. We are using nginx and php7.0-fpm, with openssl updated to the latest version. Like I said, works just fine on the server, but the moment I try on macOS, artisan doesn't return anything.

**Comment by mitsuhiko** [comment] 2016-06-23 16:41
The `composer.json` would be helpful. Also which version of composer and artisan this runs would be interesting to know.

**Comment by darkgoldblade01** [comment] 2016-06-23 16:47
Here is the `composer.json`, I had to zip it due to Github not allowing `.json` files to be uploaded. I also pasted it in case you would rather not download a file.

[composer.json.zip](https://github.com/getsentry/sentry-laravel/files/330434/composer.json.zip)

  {
      "name": "laravel/laravel",
      "description": "The Laravel Framework.",
      "keywords": ["framework", "laravel"],
      "license": "MIT",
      "type": "project",
      "require": {
          "php": ">=5.5.9",
          "monolog/monolog": "1.17.2",
          "laravel/framework": "5.2.*",
          "colling-media/teamwork": "^1.0",
          "zizaco/entrust": "dev-laravel-5",
          "doctrine/dbal": "^2.5",
          "pusher/pusher-php-server": "^2.3",
          "facebook/php-ads-sdk": "^2.6",
          "googleads/googleads-php-lib": "dev-experimental",
          "cpcstrategy/bing-ads-sdk-php": "^3.0",
          "nathanmac/laravel-guid": "dev-master",
          "graham-campbell/flysystem": "^3.0",
          "league/flysystem-sftp": "^1.0",
          "venturecraft/revisionable": "^1.27",
          "toin0u/geocoder-laravel": "@stable",
          "baum/baum": "^1.1",
          "tailored-tunes/php-slack-error-reporter": "^1.0",
          "sentry/sentry-laravel": "^0.3.0"
      },
      "require-dev": {
          "fzaninotto/faker": "~1.4",
          "mockery/mockery": "0.9.*",
          "phpunit/phpunit": "~4.0",
          "symfony/css-selector": "2.8.*|3.0.*",
          "symfony/dom-crawler": "2.8.*|3.0.*",
          "laracasts/generators": "^1.1",
          "jenssegers/rollbar": "^1.5",
          "f2m2/apidocs": "dev-master",
          "theiconic/php-ga-measurement-protocol": "^2.0"
      },
      "autoload": {
          "classmap": [
              "database"
          ],
          "psr-4": {
              "App\\": "app/"
          }
      },
      "autoload-dev": {
          "classmap": [
              "tests/TestCase.php"
          ]
      },
      "scripts": {
          "post-root-package-install": [
              "php -r \"copy('.env.example', '.env');\""
          ],
          "post-create-project-cmd": [
              "php artisan key:generate"
          ],
          "post-install-cmd": [
              "php artisan clear-compiled",
              "php artisan optimize"
          ],
          "post-update-cmd": [
              "php artisan clear-compiled",
              "php artisan optimize"
          ]
      },
      "config": {
          "preferred-install": "dist"
      }
  }

**Comment by nghtstr** [comment] 2016-06-23 16:49
Artisan Version is the following:

Laravel Framework version 5.2.39

**Comment by mitsuhiko** [comment] 2016-06-23 16:50
Cheers. Going to investigate this.

**Comment by mitsuhiko** [comment] 2016-06-23 16:57
Which command do you run that breaks?

**Comment by nghtstr** [comment] 2016-06-23 17:09
Running the command `php artisan` wouldn't issue any errors at all, it would just die.

**Comment by mitsuhiko** [comment] 2016-06-23 17:24
This is bizarre. So you are the second person that reports this but I totally cannot reproduce this (even with your composer.json). There must be another thing that is necessary to trigger this.

**Comment by darkgoldblade01** [comment] 2016-06-23 17:30
Unsure, I removed Sentry from my local copy, I got the composer.json from the server. I did modify a bunch of openssl things on my Mac to make it play nice, and that could have done something to cause it. If you aren't able to reproduce it, I wouldn't worry about it. Our server has it installed, and that is what is key. Our local machines are just the places where we make the edits. Everything saves to the server anyway.

P.S. - We didn't know this, but we actually work together, we didn't know the other sent a message to support, but both our Macs (his a MacBook 15' Retina, and mine a 27' Retina iMac, and my MacBook from 2011) all had the same issue, running different versions of macOS and OS X. Unsure what caused it to be sure, but if you aren't able to reproduce, then it was most likely something on our end.

**Comment by mitsuhiko** [comment] 2016-06-23 17:56
I'm going to keep this open for now. If someone else encounters this please paste your `composer.json` to see if there are common other dependencies in it.

**Comment by mchristie** [comment] 2016-09-14 11:22
I experienced similar issues but it turned out composer hadn't fully removed the old raven package, clearing this out fixed my issues.

**Comment by i906** [comment] 2016-11-20 06:35
I removed the files in bootstrap/cache seem to fix my similar issue.

**Comment by slobru** [comment] 2017-04-27 00:05
I removed the "::class" designation in the config file. That fixed the issue for me.

**Comment by dcramer** [comment] 2017-04-27 22:30
@slobru what version of PHP?

**Comment by slobru** [comment] 2017-04-28 14:31
@dcramer PHP 7.0.7

**Comment by stayallive** [comment] 2018-05-04 08:11
Closing this issue because it is quite old, if there is still a problem please open a new issue with your new composer file and config so we can investigate further.

**Closed by stayallive** 2018-05-04 08:11 UTC
