### ISSUE TITLE
Binary primary key issue with json_encode

### ISSUE THREAD

**Issue by kocoten1992** [getsentry/sentry-laravel#236] opened 2019-05-04 22:34 UTC
I'm using binary uuid as primary key for mysql (https://stitcher.io/blog/optimised-uuids-in-mysql) and sentry having trouble with it, because of `json_encode` https://github.com/getsentry/sentry-php/blob/master/src/Util/JSON.php#L27

dump `$data` in JSON::encode :
```
-metadata: array:2 [
  "connectionName" => "127001"
  "bindings" => array:1 [
    0 => b"õà\x1CPnä\x11ÚÖô?ÖØ SO"
  ]
```

I've try replace `JSON_UNESCAPED_UNICODE` with `JSON_INVALID_UTF8_SUBSTITUTE` or ```JSON_INVALID_UTF8_IGNORE```, which is working (but only available in php7.2)

Should I do a PR checking php version and replacing that ?

**Comment by stayallive** [comment] 2019-05-06 11:39
@kocoten1992 this seems like it could be an issue indeed, could you specify what kind of trouble you are running into? Are events not being sent or are they displayed incorrectly inside Sentry?

**Comment by kocoten1992** [comment] 2019-05-06 12:32
@stayallive thank for taking interest in this, event was unable to sent:

```
In JSON.php line 28:
                                                                                                                   
  Could not encode value into JSON format. Error was: "Malformed UTF-8 characters, possibly incorrectly encoded".  
                                                                                                                   

PHP Fatal error:  Uncaught InvalidArgumentException: Could not encode value into JSON format. Error was: "Malformed UTF-8 characters, possibly incorrectly encoded". in /var/www/myproject/releases/20190505003705Z/engine/vendor/sentry/sentry/src/Util/JSON.php:28
Stack trace:
#0 /var/www/myproject/releases/20190505003705Z/engine/vendor/sentry/sentry/src/Transport/HttpTransport.php(78): Sentry\Util\JSON::encode(Object(Sentry\Event))
#1 /var/www/myproject/releases/20190505003705Z/engine/vendor/sentry/sentry/src/Client.php(105): Sentry\Transport\HttpTransport->send(Object(Sentry\Event))
#2 /var/www/myproject/releases/20190505003705Z/engine/vendor/sentry/sentry/src/Client.php(96): Sentry\Client->captureEvent(Array, Object(Sentry\State\Scope))
#3 /var/www/myproject/releases/20190505003705Z/engine/vendor/sentry/sentry/src/State/Hub.php(140): Sentry\Client->captureException(Object(Exception), Object(Sentry\State\Scope))
#4 /var/www/myproject/releases/20190505003705Z/engine/app/Exceptions/Handler.php(38): Sentry\State\Hub->captureException(Obj in /var/www/myproject/releases/20190505003705Z/engine/vendor/sentry/sentry/src/Util/JSON.php on line 28

In JSON.php line 28:
                                                                                                                   
  Could not encode value into JSON format. Error was: "Malformed UTF-8 characters, possibly incorrectly encoded".  
                                                                                                                   
```

When I've either replace with the new JSON options:

```
In MyFile.php line 297:
                                                                          
  XERR1480: my project exception message  
                                                                          
```

**Comment by stayallive** [comment] 2019-05-08 19:55
@kocoten1992 this needs to be fixed in https://github.com/getsentry/sentry-php really but we think doing something with the JSON serializer shouldn't be needed since we should already be converting to valid UTF-8 inside the serializer, something might be going wrong there, we're looking into it!

**Comment by nikoheikkila** [comment] 2019-05-14 07:41
I can reproduce this issue using the latest Sentry integration with Laravel 5.8. Passing any kind of binary data to Sentry handler crashes it. Maybe it should run the invalid data through `bin2hex()` or some other kind of sanitizer before loading to JSON encoder?

Disabling breadcrumbs seems to work around it but I hope there will be a fix soon. I couldn't find a relevant issue from the _getsentry/sentry-php_ repo yet?

```diff
diff --git a/config/sentry.php b/config/sentry.php
index abf7d05..e82a0dd 100644
--- a/config/sentry.php
+++ b/config/sentry.php
@@ -10,4 +10,6 @@ return [
      * Specify the version of the application for Sentry.
      */
     'release' => env('APP_VERSION', 'dev'),
+
+    'breadcrumbs.sql_bindings' => false
 ];
```

**Comment by ejunker** [comment] 2019-07-12 21:30
This is an issue with `getsentry/sentry-php` See getsentry/sentry-php#828

**Comment by stayallive** [comment] 2020-03-09 13:43
This was indeed a problem in the PHP SDK this integration uses and should have been fixed a few weeks ago.

This should be fixed if you are on the latest Laravel integration (which requires the latest PHP SDK version).

If you are still running into this issue, please do open up a new issue, potentially directly on https://github.com/getsentry/sentry-php.

**Closed by stayallive** 2020-03-09 13:43 UTC
