### ISSUE TITLE
Memory issues on composer install

### ISSUE THREAD

**Issue by Christophvh** [getsentry/sentry-laravel#343] opened 2020-04-14 09:56 UTC
Hi, 

Having a lot of memory issues with sentry lately. Every time I try a composer update in a project I have to try it multiple times. Always hit memory limits. If I remove sentry it works 100%.

Today even `composer require sentry/sentry-laravel `hits my memory limit. I set my php.ini memory limit to 1G and install doesn't even work, that seems crazy.

<img width="1432" alt="Screenshot 2020-04-14 at 11 51 47" src="https://user-images.githubusercontent.com/9588070/79211281-58bfd980-7e46-11ea-904e-747e0a88bdb0.png">

Talked to a colleague and it seems that everybody has having these issues since macOS Catalina, so maybe that is related.

**Comment by stayallive** [comment] 2020-04-14 10:44
There can be many reasons why this is happening but I cannot imagine Sentry causes this (I've never encountered this yet), it might be Sentry with some other dependencies in your project where composer need to do some advanced conflict resolution to figure out what versions to install for certain packages.

Are you able to share your `composer.json` to see if I can reproduce it on my end and see if I can track down the error?

**Comment by stayallive** [comment] 2020-04-14 10:47
Closing this since you already openen an issue on the main SDK repo: getsentry/sentry-php#999.

**Closed by stayallive** 2020-04-14 10:47 UTC
Labels: support
