### ISSUE TITLE
Handling QueryException through sentry

### ISSUE THREAD

**Issue by zeshan-inquiron** [getsentry/sentry-laravel#94] opened 2017-07-30 08:26 UTC
I'm unable to monitor my 'QueryException' through sentry. As per the docs, below is my code I placed in `App\Exceptions\Handler.php@report`

```php
public function report(Exception $exception)
    {
        if ($this->shouldReport($exception)) {
            app('sentry')->captureException($exception);
        }
        parent::report($exception);
    }
```

All the other exceptions like `500`, `404` are working fine, but QueryException is not getting caught. Am I missing something here?

Thanks

**Comment by stayallive** [comment] 2017-07-30 13:29
There is no reason why it should not get caught unless it get's caught by a try/catch block or it's defined in the `$dontReport` array on your `App\Exceptions\Handler` class.

If both are not the case, can you show the code that generates the exception so I can test with it?

**Comment by stayallive** [comment] 2017-09-15 09:11
I assume you solved the problem since it's been a long time we heard from you. Closing this issue, feel free to open another with more information if the problem persists!

**Closed by stayallive** 2017-09-15 09:11 UTC

**Comment by ryantology** [comment] 2018-02-04 19:46
I had the same problem. If the issue is not the `$dontReport` It could be invalid payload. If there is binary data in the exception the `json_encode` can fail. Possibly fixed here: https://github.com/getsentry/sentry-php/pull/538 leaving comment in case of SEO.
