### ISSUE TITLE
Two Sentry issues for one exception

### ISSUE THREAD

**Issue by futzlarson** [getsentry/sentry-laravel#261] opened 2019-08-04 01:15 UTC
Ever since upgrading from `1.0.0-beta2` to `1.1.0` I am sometimes seeing two issues for a single exception, one prefaced with `Notice:`. This was one I created:

![image](https://user-images.githubusercontent.com/1168673/62418284-77bd6900-b633-11e9-9bf5-e764bc6b3757.png)

This could be happening every time, but I'm not sure as I am 2 days from launch. Is this from upgrading or something on my end?

At the time of upgrade I also stopped receiving emails for Laravel issues (but still get JS emails). I have checked my settings (that I didn't ever change) and they look correct to alert me. Anyone else?

**Comment by stayallive** [comment] 2019-08-06 16:37
@futzlarson Are you using the log channel integration next to the "normal" integration by any chance?

**Comment by futzlarson** [comment] 2019-08-08 01:08
@stayallive Honestly I don't know what you're asking.

**Comment by stayallive** [comment] 2019-08-08 09:37
@futzlarson there are 2 ways to integrate Sentry with Laravel.

This first is the recommended way: https://docs.sentry.io/platforms/php/laravel/#laravel-5x

The second is by using a so called log channel (a Laravel feature): https://docs.sentry.io/platforms/php/laravel/#using-laravel-56-log-channels

Using both can cause doubled errors, so I am wondering if you maybe have both setup in your application if not we will have to take a deeper look why this is happening, if you did setup both that explains it because if you’re using log channels to log your exceptions and are also logging exceptions to Sentry in your exception handler (as you would have configured above) exceptions might end up twice in Sentry.

**Comment by marandy0905** [comment] 2019-08-22 02:36
@futzlarson @stayallive I've been investigating through this issue recently, since we don't use the Laravel report function nor does the Log function.
We send sentry specifically in a try catch block manually. However, ever since updating 1.0.0-beta2, we've been stepping up on this issue of duplicate Log or receiving sentry notifications even if we caught the error/exception/throwable.

I think the code that has problem is here in sentry-php:
https://github.com/getsentry/sentry-php/blob/78495dd5cd68b1a01a864c1e4019556ed7a3962e/src/ErrorHandler.php#L174

This overrides the default Laravel `set_error_handler()` (https://github.com/laravel/framework/blob/195dba7ea2a68d3a49593d0de0df73c12a59fc72/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php#L43) 
no matter what, and handle the issue itself.

Therefore for the example @futzlarson is posting: will always have two sent to sentry, one from Laravel Log/Report and one for sentry-php itself

**Comment by stayallive** [comment] 2019-08-22 06:52
@marandy0905 the `set_error_handler` does not trigger for exceptions.

So it's possibly your code generates a exception but also a notice or warning (error) and you are capturing the Exception and Sentry is capturing the error?

Could you share both errors like the screenshot from Ryan with what you are getting?

@marandy0905 Also please update to the latest version, we are at `1.1.0` so we are talking about the same code, a lot of things we're fixed in the beta's.

**Comment by marandy0905** [comment] 2019-08-22 09:42
@stayallive I think I mentioned it the wrong way. But you are absolutely right about this:

> So it's possibly your code generates an exception but also a notice or warning (error) and you are capturing the Exception and Sentry is capturing the error?

The problem is that Laravel already help us catch this kind of error/notice with it's own `set_error_handler()` in the link provided above and re-throw it as an ErrorException class.

I'll show some pseudo code below with a simple API:
```
 // Set up 'report' or Log::error(); depends on your setting of sentry in Laravel

Route::get('health', function () {
    try {
        $data = [];
        $data['test'];
    } catch (\Throwable $th) {
        var_dump(get_class($th)); // 'ErrorException' 

        return response('un-oh');
    }

    return response('ok');
});
```

With the above example,
EXPECT: Receiving an 'un-oh' response, sending an ErrorException notification to Sentry.
ACTUAL: Receiving an 'un-oh' response, sent a notice error and an ErrorException notification to Sentry. The latter is triggered by the `report` function in  `App/Exceptions/Handler.php` as suggested by the official Doc in Sentry.

Since Laravel already has a fallback solution for reporting all notice/warning, Sentry-php is still 
intercepting the error_handler setting causing to sent to sentry twice.

btw, I'm working on `1.1.0` right now, and 5.8 for Laravel, the problem actually just happens starting from `1.0.0-beta2`, there's a major change of how error_handler is set since then.

**Comment by marandy0905** [comment] 2019-08-22 09:54
![螢幕快照 2019-08-22 下午5 47 48](https://user-images.githubusercontent.com/22142620/63504963-39fe8280-c505-11e9-9155-dad464c46edd.png)

more info: we're not using any Log or report function but handle Send Sentry in our own middleware.

However a fresh install of Laravel with either (only one) place implementing Sentry will reproduce.

And also we figured out to close sending to sentry by setting `'error_type' => 0` in sentry config. This works well by not sending the unexpected notice/warning but still send the ErrorException one.

**Comment by futzlarson** [comment] 2019-08-22 14:26
@stayallive FYI I am only doing the recommended way. And as @marandy0905 mentioned, this only started happening once I upgraded. Side note, it doesn't seem to happen every time.

**Comment by futzlarson** [comment] 2019-09-03 22:48
Any update @stayallive?

**Comment by SCIF** [comment] 2019-09-09 01:16
Guys, that's because of [Sentry's integrations](https://github.com/getsentry/sentry-php/blob/master/src/ClientBuilder.php#L111). They handle errors before laravel's handler does it.

**Comment by futzlarson** [comment] 2019-09-14 18:34
@SCIF But this is something that only started happening in recent versions?

**Comment by SCIF** [comment] 2019-09-15 23:20
Probably this one [introduced it](https://github.com/getsentry/sentry-laravel/pull/239/files#diff-7909ebf476ca6661eff733fee6956dfdR117). Not sure. I still doesn't have enough time to investigate that.

**Comment by airgrim** [comment] 2019-09-25 11:42
Sentry registers it's own [error handler](https://github.com/getsentry/sentry-php/blob/master/src/ErrorHandler.php#L175), which reports given error.
And runs previous error handler after, which might throw an exception. This last exception is reported by aSentry also

**Comment by airgrim** [comment] 2019-09-25 15:47
probably can be fixed with `sentry.php` config:
```
<?php

return [
    'error_types' => ~E_ALL,
];
```

**Comment by hurie** [comment] 2019-10-07 11:54
I found that, client builder have default integration of ExceptionListenerIntegration which register error handler. So put captureException in error handler or add logging in application will duplicate log.

**Comment by stayallive** [comment] 2019-10-07 11:57
We are working on seeing if #280 solves the issue which is most likely the best "fix" for the issue without us missing issues (takes a bit of time to test).

**Comment by hurie** [comment] 2019-10-07 15:12
I try #280 and it fixed duplicate log. I'll wait for release. For now, I'll remove captureError on laravel handler.

**Closed** 2019-10-15 09:25 UTC
Labels: support

**Comment by stayallive** [comment] 2019-10-18 07:09
This issue was closed however I never mentioned we think it's fixed in `1.4.0`, please do open it back up or open a new issue if the problem is not solved.

**Comment by futzlarson** [comment] 2019-10-18 17:52
`1.4.1` is working fine for me - thanks!

**Comment by carestad** [comment] 2020-02-11 12:30
I have recently started seing double exceptions being reported again now recently. Is this just me, or was something changed in 1.6.X perhaps?

**Comment by stayallive** [comment] 2020-02-12 12:51
@carestad it shouldn't 😄 but please do open a new issue with the information you have and maybe both exceptions (as much as you can/are willing to share) so we can investigate!

**Comment by cyreb7** [comment] 2020-02-13 20:06
@carestad We've also been seeing issue this again.

The regression seems to be caused by sentry-php 2.3. I forced `"sentry/sentry-laravel": "1.5.*"` and switched between `"sentry/sentry": "2.2.*"` and `2.3.*`, calling `return 1/0;` on 2.2 sends one error to Sentry, but on 2.3 I get two.

**Comment by stayallive** [comment] 2020-02-13 21:33
Yes, as mentioned in #327 this problem is caused by `sentry/sentry:^2.3` and will be fixed shortly for now pinning to `sentry/sentry-laravel:1.5.*` and `sentry/sentry:2.2.*` is a immediate fix if you need it.

**Comment by stayallive** [comment] 2020-02-14 13:15
`sentry/sentry-laravel` `1.6.2` was just released which fixes the regression causing duplicate exceptions, thanks all for the information and patience!
