### ISSUE TITLE
OutOfBoundsException Package "sentry/sentry" is not installed

### ISSUE THREAD

**Issue by johanehnberg** [getsentry/sentry-laravel#491] opened 2021-05-25 05:30 UTC
### Environment
Ubuntu 20.04 with stock Composer 1, PHP 7.4

### How do you use Sentry?
self-hosted/on-premise for a Laravel app using sentry-laravel

### Steps to Reproduce

Our installs are currently blocked due to composer throwing this error since 24 May 2021. When running any composer command such as dump-autoload, install or update, it currently generates an error:

$ sg www-data 'composer dump-autoload'
Generating optimized autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

   OutOfBoundsException 

  Package "sentry/sentry" is not installed

  at vendor/composer/composer/src/Composer/InstalledVersions.php:166
    162▕ 
    163▕             return $installed['versions'][$packageName]['pretty_version'];
    164▕         }
    165▕ 
  ➜ 166▕         throw new \OutOfBoundsException('Package "' . $packageName . '" is not installed');
    167▕     }
    168▕ 
    169▕     /**
    170▕      * @param  string      $packageName

      +17 vendor frames 
  18  app/Exceptions/Handler.php:47
      app()

      +2 vendor frames 
  21  [internal]:0
      Illuminate\Foundation\Bootstrap\HandleExceptions::handleException()
Generated optimized autoload files containing 11178 classes

#### There are indications this is a bug in one or a combinations of the following components:

    laravel-sentry
    composer (particularly version 1 vs 2)
    phpstan
    ocramius/package-versions or whichever variant we have

### Similar threads:

https://github.com/getsentry/sentry-laravel/issues/274
https://github.com/getsentry/sentry-symfony/issues/383

**Comment by dialyy** [comment] 2021-05-25 08:11
The fix : upgrade composer 1 to V2

the cause : package suggestions and new dependencies not handled anymore by composer 1 so maybe skip or always trying go backward

**Comment by stayallive** [comment] 2021-05-25 12:54
@Jean85 are you able to provide some insight in why this could be happening?

**Comment by Arkanius** [comment] 2021-05-25 20:05
> the cause : package suggestions and new dependencies not handled anymore by composer 1 so maybe skip or always trying go backward

Isn't it considered as a BC?

**Comment by filakhtov** [comment] 2021-05-26 06:14
We just ran into this issue as well. Happened after routine `composer update`. Using composer v1.10.22. Would appreciate any insights into the issue.

**Comment by stayallive** [comment] 2021-05-26 08:52
So that was quick :D It should all be good now after a `composer update`, please let me know if it's all back to working now!

**Comment by filakhtov** [comment] 2021-05-26 09:45
Thanks for the update! Did not work for me... because we are on `jean85/pretty-package-versions` version `1.6.0`. Asked upstream if we can get this backported 🤞🏻

**Comment by Jean85** [comment] 2021-05-26 11:12
As I already answered there, in that case the fix is elsewhere, here: https://github.com/composer/package-versions-deprecated/pull/25

That is released too, so you just need to `composer update composer/package-versions-deprecated`.

**Comment by filakhtov** [comment] 2021-05-26 13:23
Hey @Jean85, thanks for the clarification, but I am still seeing issues. I am on `composer/package-versions-deprecated` version `1.11.99.2` and consistently seeing:
```
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover

   OutOfBoundsException 

  Package "sentry/sentry" is not installed

  at vendor/composer/composer/src/Composer/InstalledVersions.php:166
    162▕ 
    163▕             return $installed['versions'][$packageName]['pretty_version'];
    164▕         }
    165▕ 
  ➜ 166▕         throw new \OutOfBoundsException('Package "' . $packageName . '" is not installed');
    167▕     }
    168▕ 
    169▕     /**
    170▕      * @param  string      $packageName

      +24 vendor frames 
  25  [internal]:0
      Illuminate\Foundation\Application::Illuminate\Foundation\{closure}(Object(Sentry\Laravel\ServiceProvider))

      +5 vendor frames 
  31  artisan:37
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```
on `composer install`. @stayallive any other ideas what that might be?

Running PHP 7.4.16 on macOS 10.15.7 if that matters.

**Comment by filakhtov** [comment] 2021-05-27 06:44
Coming back to report the progress we had while investigating this issue. Turned out that one of our indirect dependencies pulled in `"composer/composer": "(^1.6||^2)"` resulting in composer favouring the latest version and pulling in v2, resulting in incompatibilities and breakages. Pinning `composer/composer` to `^1` in the project resolved the problem.

**Comment by Jean85** [comment] 2021-05-27 07:20
Thank you for reporting back. I highly encourage you to upgrade to Composer 2 though, it has a nice performance boost and nearly no breaking changes.

**Comment by filakhtov** [comment] 2021-05-27 07:59
@Jean85 yeah, that's absolutely something we will be doing in the nearest future... just requires quite a bit of investment on our side to audit everything and ensure smooth transition.

**Comment by kosmonowt** [comment] 2021-05-29 16:41
Having that problem here as well. We can not shift fo composer 2 currently, there are some packages in our project that are not (yet) compatible. Please make that work again. I can not deploy my application without a fix in that.
`composer update composer/package-versions-deprecated` does not work.

**Comment by Jean85** [comment] 2021-05-31 16:24
@kosmonowt that's not our fault. If you are having this issue, it means that you upgraded Composer to the latest patch, and the latest `composer/package-versions-deprecated` patch should've fixed that.

In any way, we've already fixed what we could; check which versions of Composer and `composer/package-versions-deprecated` are you using, since it should be already fixed with the latest patches.

**Comment by kosmonowt** [comment] 2021-05-31 16:34
> @kosmonowt that's not our fault. If you are having this issue, it means that you upgraded Composer to the latest patch, and the latest `composer/package-versions-deprecated` patch should've fixed that.
> 
> 
> 
> In any way, we've already fixed what we could; check which versions of Composer and `composer/package-versions-deprecated` are you using, since it should be already fixed with the latest patches.

Thanks!

I managed to upgrade that project to composer2.

Now it works anyhow.

**Comment by stayallive** [comment] 2021-05-31 16:38
I believe there is a solution now and the problem should be solved. Thanks @Jean85 for jumping in!

If you are still having issues please do open up a new issue so we can investigate further! 👌

Thanks all!

**Closed by stayallive** 2021-05-31 16:38 UTC
