### ISSUE TITLE
Scope data in queue jobs are lost

### ISSUE THREAD

**Issue by arminulrich** [getsentry/sentry-laravel#342] opened 2020-04-11 19:12 UTC
Version: **v1.7.0**

Problem: **Adding extras/tags in a queue-jobs handle() method are not being pushed to sentry**

## How to reproduce:

I created a TestSentryJob like this:

```php
public function handle()
{
    dump("TestSentryJob is running..");

    configureScope(function (Scope $scope)
    {
        $scope->setTag("testtag","test");
        $scope->setExtra("testid","id");
    });

    throw new \Exception("test");
}
```

If I run that in Sync mode it works, **if I run it via the Database Queue Driver, the extra+tag is not being pushed.**

I further added some logging to the following files:

`./sentry-laravel/src/Sentry/Laravel/EventHandler.php:beforeQueuedJob()`
`./sentry-laravel/src/Sentry/Laravel/EventHandler.php:afterQueuedJob()`

```php
private function beforeQueuedJob()
{
    // When a job starts, we want to push a new scope
    dump("We push a new Scope");
    SentrySdk::getCurrentHub()->pushScope();
}

private function afterQueuedJob()
{
    dump("We pop the scope");
    // Flush any and all events that were possibly generated by queue jobs
    Integration::flushEvents();

    // We have added a scope when the job started processing
    SentrySdk::getCurrentHub()->popScope();
}
```

`./sentry/sentry/src/State/Hub.php:captureException`

```php
public function captureException(\Throwable $exception): ?string
{
    $client = $this->getClient();

    dump("We capture the Exception");

    if (null !== $client) {
        return $this->lastEventId = $client->captureException($exception, $this->getScope());
    }

    return null;
}
```

which results in the following output:

```
"We push a new Scope"
[2020-04-11 18:53:28][827] Processing: App\Jobs\TestSentryJob
"TestSentryJob is running.."
[2020-04-11 18:53:28][827] Failed:     App\Jobs\TestSentryJob
"We pop the scope"
"We capture the Exception"
```

It looks like the scope is getting killed **before** its captured

(If I am removing the pop/push in the before and/or after QueuedJob Events, the correct scope gets pushed along with the error)

## Possible Solutions:

As I'm not very familiar with your codebase I'm not sure why you need push/pop the Scope for every queue QueueJob (I imagine that is for the Daemon mode which won't kill the current process.) - my thought was to (only) start a fresh Scope with every job 

Might be worth looking into the `Looping` Event which gets fired Laravel decides if the Daemon should keep on running 🤷‍♀️

**Comment by stayallive** [comment] 2020-04-12 15:55
The scope is popped to prevent a buildup of breadcrumbs unrelated to the current running job and / or overlapping scope data when indeed running in daemon mode, the process never exits so the scope is never reset.

I'm not a 100% sure why the sync queue does work correctly but it probably has something to do with the order in which the exceptions are handled.

The looping event can't be used either unfortunately, for context: #318.

I will see if I can reproduce and work up a fix for this because it does seem the scope is popped to soon indeed.

What version of Laravel are you on?

**Comment by arminulrich** [comment] 2020-04-13 07:22
I just realized this project was quite far behind - Laravel 5.8

but on a fresh Laravel 7 install same thing:
```
"We push a new Scope"
[2020-04-13 07:08:13][2] Processing: App\Jobs\TestSentryJob
"TestSentryJob is running.."
[2020-04-13 07:08:13][2] Failed:     App\Jobs\TestSentryJob
"We pop the scope"
"We capture the Exception"
```

**Comment by stayallive** [comment] 2020-04-15 11:06
I've tracked down the issue to how Laravel handles and throws exceptions in jobs.

The `JobExceptionOccured` event fires before the error is caught by the framework (which makes sense), but presents problems in our case because we can't use that event to pop the scope because that is too soon causing the behaviour you are experiencing.

https://github.com/laravel/framework/blob/cac4a74cc6613ab4d413a17276334b8d2f4f324c/src/Illuminate/Queue/Worker.php#L375-L408

Although I'm not sure why in `sync` mode it would work since that uses the same flow.

Still working on this!

**Comment by stayallive** [comment] 2020-04-15 11:58
The more I think about it the more tricky this is getting :)

So the reason for the push/pop dance it to be able to have a queue job run in isolation (from a scope point of view which contain breadcrumbs/tags/context etc.).

So the current events are (in that order):

- `Looping` (only in daemon mode)
- `JobProcessing`
- `JobProcessed` (unless an exception occurs)
- `JobExceptionOccurred` (only if an exception occurred)
- exceptions are caught by Laravel here and processed by Sentry
- `WorkerStopping` (only if the queue is actually stopping
- `Looping` (only in daemon mode)
- starting from the top again...

That's why the `Looping` event is perfect for popping the scope and the `JobProcessing` is the perfect for pushing a scope.

However when not in daemon mode we are missing the `Looping` event leaving us with nothing to replace it...

My current thought is:

> Flipping a flag in our event handler so we can track if we pushed a scope before and pop it before pushing a new one on `JobProcessing` (and in addition clearing the data in that scope to make sure it's clean).

The downside to this approach is the sync queue will never pop the scope. For jobs that throw an exception this is not an issue since that will crash the current request and that be caught. 

We could then use `JobProcessed` to pop the scope if the job ran cleanly (using our internal state to track if we should pop the scope in the first place).

I would probably bring back the `Looping` event to flush the event queue since that will work better than the current way when running in daemon mode.

How does this sound to you?

**Comment by arminulrich** [comment] 2020-04-16 17:25
I think this is a good approach.

This downside (with the sync queue, never poping) should be less of an problem IMO - you shouldn't have multiple of the same sync-queued-jobs in a row right?

Maybe as a different Idea - could we push/pop scopes in a specific namespace? f.ex:

```
private function beforeQueuedJob()
{
    SentrySdk::getCurrentHub()->pushScope(get_class($sentryJob));
}

...
public function pushScope($namespace): Scope
{
    $clonedScope = clone $this->getScope();

    $this->stack[$namespace] = new Layer($this->getClient(), $clonedScope);

    return $clonedScope;
}
```

This would allow us to do something like a `scopeUnset/Reset/Clear` in `JobProcessing` and just for that Job. Maybe even a `"queue"` namespace could be enough

**Comment by HazAT** [comment] 2020-04-27 17:32
@stayallive Can we maybe create a new hub instance just for the jobs?
That would kinda "emulate" the namespaced scope

**Comment by stayallive** [comment] 2020-04-29 07:11
I don't think that solves anything really.

This is because we need to be able to restore the correct hub, so pushing/popping a scope is as simple.

The "problem" is that you can have queue jobs run inside a web request using the so-called "sync" queue, but this would need the current hub/scope and need it to be correctly restored/popped.

So I don't think that adds less complexity.

I think the current plan (I need to make a PR for and test) is the most simple:

> Flipping a flag in our event handler so we can track if we pushed a scope before and pop it before pushing a new one on JobProcessing (and in addition clearing the data in that scope to make sure it's clean).

Happy to be proven wrong though if I missed something.

**Comment by stayallive** [comment] 2020-05-28 19:38
I am sorry for the delay here but I think I've got an pretty good solution going.

Please check out #351 and let me know if you have any problems/suggestions.

**Closed** 2020-05-31 11:41 UTC
Labels: bug
